### PR TITLE
idle fix

### PR DESCRIPTION
**Pull request by loginekuy**
Web WhatsApp has an idle time, once this amount of minutes are reached, it will not show anymore the "online" status. I've added a loop that clicks every 10 seconds on the username, trying to avoid this idle issue.

### CODE REVIEW

**Comment by jasperan** [comment]
Hi @loginekuy the issue I find with your commit is that it breaks the flow of the code, there's a while True: operation already in line 85, if you put a while where you're putting it you're not allowing the program to get to that loop and therefore won't be able to log anything.

Can you amend the logic of your program, test it and update this pull request please?

**Review by jasperan — CHANGES_REQUESTED** [review]
Hi @loginekuy the issue I find with your commit is that it breaks the flow of the code, there's a while True: operation already in line 85, if you put a while where you're putting it you're not allowing the program to get to that loop and therefore won't be able to log anything.

Can you amend the logic of your program, test it and update this pull request please?

**Comment by loginekuy** [comment]
I'm sorry about that. I didn't realize. So, given that we need to somehow execute some action on the web whatsapp page every some short period of time to avoid IDLE, I thought 2 different approaches: 

1) Make a focus on web whatsapp window.
2) Make a click, I think making a click would be really more practical. I've done the modifications for this.

I have opted for the 2nd choice. I hope it helps, give it a try.

Also, I will try to fix other issues I've detected in your code later.

Have a nice day.

**Review by jasperan — APPROVED** [review]

**Comment by jasperan** [comment]
Awesome @loginekuy approved!

**Pull request merged**
