### PR TITLE
Your data is accessible in excel file and a readme document in Turkish has been added

### PR DESCRIPTION
**Pull request by BerkeGokturk71**
You can See your data in Excel format and Turkish language support added.Chrome driver updated for new chrome versions.
"-e" parameter create your excel file.Now Readme File support Turkish language.I added samples.Finally I did some  code reviews.

### CODE REVIEW

**Review by jasperan — CHANGES_REQUESTED** [review]
Please, remove from your local (or empty) the following pull request, or add them to your .gitignore so they are not included in the PR:
- database/database.db
- chromedriver.exe

Also, remove .pyc files from the commit so we don't include compiled code that won't serve to other users!

**Comment by BerkeGokturk71** [comment]
I added database folder and excel file and deleted the pyc folder from there.

**Comment by BerkeGokturk71** [comment]
Okay I deleted chromedriver.exe . Anything else because  I'm junior python developer :)

**Comment by jasperan** [comment]
congrats @BerkeGokturk71 this is a good Pull RequesT!

**Pull request merged**
